### ISSUE TITLE
"Assume everything is artifice" appears to be always on even when toggled off

### ISSUE THREAD

**Issue by j2udevelopment** [Mijago/D2ArmorPicker#100]
I noticed that, with or without the "Assume everything is artifice" feature toggled on, the output mistakenly claims that the gear is artifice.

For some more information, I also have it limited to only show artifice armor in the armor limitation section, but it's still spitting out non-artifice armor.

This is for version 2.3.0

![image](https://user-images.githubusercontent.com/6598273/226176619-0facc1b7-ef21-4c1b-b865-e3fa5d103f90.png)

**Comment by TheMojoDojo** [comment]
This feature was used mainly for testing, as some members did not have artifice armor, yet still needed to be able to simulate artifice armor.

That toggle makes D2AP think that every armor applicable is artifice. We wouldn't recommend it's use for daily use

**Comment by j2udevelopment** [comment]
Understood, but I'm saying that the toggle _appears_ to always be on

**Comment by j2udevelopment** [comment]
Looks like something got cached in my browser when I toggle that on. I emptied cache and hard reloaded and it's good to go!  Apologies for the false alarm!

**Comment by Mijago** [comment]
For clarification, the setting tells the inventory refresh to always set the armor perk to "Artifice". This inventory refresh is only executed after a reload (as stated in the tooltip). That's why it was not deactivated instantly :)
