### ISSUE TITLE
Create a maintenance banner

### ISSUE THREAD

**Issue by Mijago** [Mijago/D2ArmorPicker#105]
Right now, D2AP logs you out when the API is unavailable and does not give any further information.

Goals of this ticket:
- Create an "API unavailable" banner or subpage
- Catch API errors and then show the banner or forward to the subpage

Related issues:
- https://github.com/Mijago/D2ArmorPicker/issues/98

**Comment by TheYeshir13** [comment]
Should be fixed in 2.6.0
