### ISSUE TITLE
Add documentation for developers

### ISSUE THREAD

**Issue by THATDONFC** [Mijago/D2ArmorPicker#116]
I recently decided to contribute to D2AP because I enjoy using the tool and love working on open source projects. I think it's important to attract contributors in order for these types of projects to survive and thrive. When I first attempted to contribute to D2AP I ran in to a number of challenges and issues that took a bit of searching to figure out. The process was not as simple as the readme instructions outlined. 

Here's where I struggled the most:

- Creating a D2 application and obtaining the necessary API keys for testing
- Serving the changes locally to preview rather than deploying to gh-pages
- Building and deploying the project with the changes
- In [`package.json`](https://github.com/Mijago/D2ArmorPicker/blob/master/package.json#L9) the `deploy` command contains a `--cname` configuration which creates a problem when deploying to any repo other than Mijago/D2AP. The same goes for the `deploy-beta` command.
- In my new environment, `environment.prod.ts` did not exist. It was not clear to me how this file was generated. I ended up creating one from the `environment.ts` file that was generated by `set-env.ts`.

In my opinion, adding some developer documentation would invite more contributors. Modifying some of the configuration files so they work better in repos other than the original repo would also be a welcome change. I suggest using custom workflows for deploying production and beta builds. 

I am familiar enough with the project now to implement my own workarounds for these challenges. Another contributor might turn away if they feel the trouble is not worth their time.

**Comment by Mijago** [comment]
I did something! Please have a look at https://github.com/Mijago/D2ArmorPicker/pull/120

**Comment by Mijago** [comment]
I merged it. We can always improve upon it. If there is anything else that has to be added, feel free to reopen this issue and/or to open a Pull Request.
