### ISSUE TITLE
Prepare project for collaboration 

### ISSUE THREAD

**Issue by Mijago** [Mijago/D2ArmorPicker#117]
This one is entirely on me.
Todo:

- [x] Create a contributor documentation, see https://github.com/Mijago/D2ArmorPicker/issues/116.
- [x] Streamline used tools. 
- [x] Add git linter (husky) 
- [x] Add code linter. 
- [ ] Finally pick a license. I am picky here.

I might add more todo entries over time.

**Comment by mfasman95** [comment]
+1 for husky. I've found it very easy to work with in the past.

**Comment by Mijago** [comment]
> +1 for husky. I've found it very easy to work with in the past.

I only set it up once to test it - @mfasman95  do you have information about pitfalls, best practice and other things?
Maybe even a nice repository of good default settings? I know there is an Angular template (as the Angular repository uses it). I will look into it in detail on Tuesday, but maybe you can already share some information to make this a bit easier. :)
