### ISSUE TITLE
SSL error cannot provide secure connection

### ISSUE THREAD

**Issue by jpmaradiaga** [Mijago/D2ArmorPicker#12]
On: https://localhost:4200/

![image](https://user-images.githubusercontent.com/44245417/127697963-1f50edb2-e085-47ac-a6be-2ee3d6a9aa7d.png)

**Comment by Mijago** [comment]
Why are you even trying to connect to localhost?

**Comment by jpmaradiaga** [comment]
I downloaded the repo to see if I could help troubleshoot the login issue.

**Comment by Mijago** [comment]
Ah, did not realize that. I am sorry :)
This is a normal "bug", just replace https with http. Sadly I also have to do this on every relog.
