### ISSUE TITLE
[Feature Request] Add option to not use an artificer class item or add guardian games mod slot

### ISSUE THREAD

**Issue by TheYeshir13** [Mijago/D2ArmorPicker#134]
Requested on discord by MightyKibbles96#4656 and Jacob#7125

Reason:
Want to use a Guardian Games Class emblem.

Either add mod slot for guardian games (if possible) or add an option to force the use of a non artificer slot

**Comment by Mijago** [comment]
The guardian games requires a specific class item. Does the one from previous seasons also count, or just the current one?

Mit freundlichen Grüßen / Best Regards
Alexander M. Frühwald
________________________________
From: TheYeshir ***@***.***>
Sent: Wednesday, May 3, 2023 6:42:17 AM
To: Mijago/D2ArmorPicker ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Mijago/D2ArmorPicker] [Feature Request] Add option to not use an artificer class item (Issue #134)


Requested on discord by MightyKibbles96#4656 and Jacob#7125

Reason:
Want to use a Guardian Games Class emblem.

Either add mod slot for guardian games (if possible) or add an option to force the use of a non artificer slot
