### ISSUE TITLE
Kicks me back to the login page as soon as I login and enter the site

### ISSUE THREAD

**Issue by hellobossv5** [Mijago/D2ArmorPicker#139]
https://github.com/Mijago/D2ArmorPicker/assets/133064337/4d7d4620-f942-4249-92da-2430c9923eb4

**Comment by heymustache** [comment]
came here to report the same. tried it in firefox and chrome. signing in through xbox on bungie's site.

**Comment by heymustache** [comment]
my bad - bungie servers are still down for maintenance it seems

**Comment by Reynbow** [comment]
same thing here even now, while the servers are up

**Comment by Mijago** [comment]
This will be more visible with #105.
I will close this issue for now - sadly we can not do anything else than waiting :/
