### ISSUE TITLE
Resiliance stat tooltip displays old data

### ISSUE THREAD

**Issue by bgmonroe** [Mijago/D2ArmorPicker#159]
It looks like the Resilience stat tooltip is showing old data.  Specifically the data prior to PvE damage reduction nerf, so at 100 Resil, the tooltip says PvE DR is 40%, then 32, etc.  It looks like [from here ](https://github.com/Mijago/D2ArmorPicker/blob/26ef48971605ae40c7ac00a047fb2c8ab08044b0/src/app/components/authenticated-v2/overlays/stat-cooldown-tooltip/stat-cooldown-tooltip.component.ts#L110) that it's hard-coded in the tooltip.  From reading around, I got the impression that D2ArmorPicker made use of [Database-Clarity/Character-Stats](https://github.com/Database-Clarity/Character-Stats) but [their data ](https://github.com/Database-Clarity/Character-Stats/blob/master/legacy-content/v1.5.0/CharacterStatInfo.json#L260) looks up-to-date.

**Comment by bgmonroe** [comment]
Ah, looks like  #110 would fix this when/if it ever gets merged.

**Comment by Mijago** [comment]
This will be fixed with https://github.com/Mijago/D2ArmorPicker/pull/157 (which is merged). I will deploy it soon-ish.
