### ISSUE TITLE
Auto logout

### ISSUE THREAD

**Issue by Plasmafury23** [Mijago/D2ArmorPicker#167]
The moment I log in, it immediately logs me out.
Any fixes, or is it something i'm doing wrong?

**Comment by jhilker98** [comment]
I've also encountered this issue.

**Comment by TheMojoDojo** [comment]
Hey, this currently Destiny is undergoing maintenance, and as a result no 3rd party apps are able to access the API. It should be back once Destiny is up and running

**Comment by jhilker98** [comment]
Thanks!

**Comment by Marcossms8** [comment]
eu logo e sair da tela pedindo para conecta dnv

**Comment by TheYeshir13** [comment]
![image](https://github.com/Mijago/D2ArmorPicker/assets/88265590/fc3b6d68-7cd7-4627-bdac-f12721801060)
 This is fixed with Version 2.6.0

**Comment by TheYeshir13** [comment]
![image](https://github.com/Mijago/D2ArmorPicker/assets/88265590/b698a613-2b47-4c97-82d7-32a94cc8a530)
This is fixed with version 2.6.0
