### ISSUE TITLE
 want let me log in 

### ISSUE THREAD

**Issue by jstorm270** [Mijago/D2ArmorPicker#177]
i have tried to log in on 3 different browsers and it still will not work it asks me to sign in so i go in with my steam account and it acts like it is going to log in then kicks back out to the log in page

**Comment by TheMojoDojo** [comment]
Its more likely that the API is down for maintenance

**Comment by SilentGlasses** [comment]
I am currently experiencing the same issue. It logs me in, starts to load my profile then just drops me back to the login screen. DIM, LightGG, and D2 Checklist work just fine so not sure it's the API.

**Comment by SilentGlasses** [comment]
Just got kicked out of all tools..

From Bungie Help:

> DESTINY 2 MAINTENANCE
> ❖ Update 7.3.6
> 
> Background maintenance will remain extended as we continue investigating server stability, quest progression, and reward issues.
> 
> Updates will be provided when available.

**Comment by RAIST5150** [comment]
Leaning towards issues from Bungie's end as well.  Was working fine last night and this morning at work.  The webapp appears to be struggling to poll my inventory... looks like it tries to refresh the greyed out exotic list, then drops back to the login page.

Their Companion app was still squirly at dinner time and the line from their end was about bungie.net services being down for maintenance. While things are now working... it is pretty sluggish.

**Comment by shadowbreak200** [comment]
yeah im having the same exact problem i hope it can get fixed soon as im trying to aim for triple 100 stat armor.

**Comment by jstorm270** [comment]
i am having the same issue i have never used it before and i have been
trying to log in for a week now and it acts like itsgoing to sign me in but
then goes back to the log in page

**Comment by Mijago** [comment]
Fixed - Bungies vendor API was still down.
