### ISSUE TITLE
D2 armor picker automatically logging users out

### ISSUE THREAD

**Issue by Shizzxx** [Mijago/D2ArmorPicker#178]
I’m using d2 armor picker 
via the chrome browser on my mobile device. I can sign in then it tries to gather data for a few seconds and then immediately crashes. I tried using the safari browser and have the same issues.

**Comment by TheYeshir13** [comment]
![image](https://github.com/Mijago/D2ArmorPicker/assets/88265590/5064c10a-aaef-4bbf-a63e-a3b99bb2d58b)
This is fixed with version 2.6.0,
