### ISSUE TITLE
Save builds

### ISSUE THREAD

**Issue by TheYeshir13** [Mijago/D2ArmorPicker#18]
"Save builds"? Maybe use localStorage or cookies, a section to save a configuration and give it a name/tag, like "GM Shadebinder".

Source: https://www.reddit.com/r/DestinyTheGame/comments/otu52u/easy_browser_based_gear_selection_tool_for_stat/h6zcgrz/?utm_source=share&utm_medium=web2x&context=3

**Comment by Mijago** [comment]
Already implemented in #24 and #22.
