### ISSUE TITLE
Stasis Fragment Whisper of Torment is not an option

### ISSUE THREAD

**Issue by Soup443** [Mijago/D2ArmorPicker#188]
Whisper of Torment on Stasis is currently not an option to in the Stat Boost Stasis Selection

**Comment by TheYeshir13** [comment]
![image](https://github.com/Mijago/D2ArmorPicker/assets/88265590/974c0ab6-19d8-4865-9c12-4a7bf1a441b1)
This was changed to have a -10 to discipline
