### ISSUE TITLE
Bug: D2AP is miscalculating Mobility stats when Powerful Friends is equipped 

### ISSUE THREAD

**Issue by AOstarello** [Mijago/D2ArmorPicker#27]
Great app, love the design, and it's pretty helpful.  Just bought ya a coffee.  :)

Running into a small issue with a particular piece of armor.  It's a masterworked Scorned Baron Vest, on the account ObiDosKenobi (PS4).   It has 31 Mobility (29 base + 2 MW).  

1)  Initially, D2AP thought it had 22 Mobility, which is an error.  All other stats were correct.  At the time it had the following mods equipped: Recovery, Powerful Friends, 2x Unflinching Pulse Rifle Aim (from the seasonal artifact).  That had taken its Mobility to 41 (29 base + 2 MW + 20 Powerful Friends).  
  - Perhaps important (but probably not), I had equipped the Unflinching Pulse Rifle Aim Mods a week ago, and THEN reset my artifact (and didn't re-pick Unflinching Pulse Rifle Aim.  Realized this while I was investigating how D2AP had different Mobility stat than DIM and D2Checklist.

2)  I removed all the mods from the Vest, and requeried D2AP.  Now, it shows up correctly, as a 31 Mobility Vest.  

3)  I added the Powerful Friends mod back onto the piece and equipped it (with Radiant Light on a different armor piece).  This takes the Mobility to 51 (and note that D2 actually applies the 51 to the total stat calculation), but the piece in the D2 interface only displays up to +42.   Requeried D2AP.  Now the piece shows back up as 22 Mobility - incorrect.

Conclusion:  Something about Powerful Friends taking the Mobility stat across the +42 display limit confuses D2AP and makes it alter (wrap around?) the Mobility number.  This leads to erroneous calculations when calculating armor sets.

Interim fix:  Remove Powerful Friends and Radiant light from all armor pieces before running D2AP.  

Hope this is replicable, and that it helps.  Happy to assist more if this is unclear.

**Comment by Mijago** [comment]
Thank you for your report.
I close this in favor of #29.
