### ISSUE TITLE
Optimize item parsing when a mod with a bonus or penalty is equipped

### ISSUE THREAD

**Issue by Mijago** [Mijago/D2ArmorPicker#29]
Currently, when an item is parsed, D2AP takes the stats taken from the API and adds/removes the stats given by any equipped Mods. If the item is masterworked, it then reduces all stats by 2.

Problem: The API caps all stats between 0 and 42.
If an item has a base stat of 4 strength and you equip Protective Light, it then has -6 strength. The Api only returns 0, which results in the tool thinking it has 8 strength (0+10-2).

Fix: currently unknown. DIM had this bug for a long time but fixed it a few weeks ago, so investigating this would probably help. _Any help appreciated._

**Comment by SpencerCarstens** [comment]
Does this bug also cover the issue of armor pieces with too high of stats not showing up as potential matches in the tool?

**Comment by Mijago** [comment]
> Does this bug also cover the issue of armor pieces with too high of stats not showing up as potential matches in the tool?

Yes.

**Comment by Mijago** [comment]
This issue has been fixed a long time ago.
