### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by chrisyaren** [Mijago/D2ArmorPicker#30]
I went to login today and it brought me to the "choose your platform page"...
https://www.bungie.net/en/User/JoinUp?client_id=37252&response_type=code&bru=%2Fen%2FOAuth%2FAuthorize%3Fclient_id%3D37252%26response_type%3Dcode

I then clicked xbox...and without asking me for credentials it just brought me to this page...https://www.bungie.net/en/User/AuthError?id=25 

... I cannot seem to get around this error..even though I am logged in with my xbox account...chrome/windows.

tried on firefox..asked for credentials...and redirected to same error page.

**Comment by Mijago** [comment]
This is a Bungie.net Login issue and not related with this tool. The login is down for the whole page.
But thanks for the report!
