### ISSUE TITLE
Kick-off buildPermutations & updateTable on demand instead of ngOnInit

### ISSUE THREAD

**Issue by nazimamin** [Mijago/D2ArmorPicker#34]
Currently, you're kicking-off `this.permutations = this.permBuilder.buildPermutations(allArmor)` in `updateItemList` and `updateTable` within `ngOnInit`. This will make the site unresponsive when a user has a lot of Armors. 

It'd be great if this can be triggered manually after the user has chosen the Tier list/exotic/mods.

**Comment by ParasiticUniverse** [comment]
I can confirm that this makes the site not work for me. I have 243 pieces of Warlock armor and the site hits the Chrome ram limit.

**Comment by Mijago** [comment]
The site will hit the limit, no matter _when_ I load the data.
Note that this is fixed in v2, check the v2 branch for this. You can always use add /v2 after the # to use v2.

**Comment by nazimamin** [comment]
I double-checked on v1, didn't realize that no filters are done until permutation is complete so you're right about that.

Great work on V2. Worker improves the performance for a small number of permutations. But you'll still run out of memory for a large number of armors (take 150 worst case) when creating multi-dimensional arrays like you're doing.

**Comment by Mijago** [comment]
Hi, I everything is written in byte arrays and even compacted into one int, whenever possible, especially to save memory.
And the results table then translates the first 250k entries (except when this number is overwritten) to visualize them.

I tested the tool with 400 armor entries on a 16gb ram pc and a 32gb pc. It may take a while, but when you have over 350 armor items for one class, you may have another problem, hehe.
