### ISSUE TITLE
Out-of-Memory Crash

### ISSUE THREAD

**Issue by BastaAZ** [Mijago/D2ArmorPicker#35]
I have a full vault, and really only play a single character.  So nearly all of the gear is for a single class.  When I load the tool up using that class, it crashes.  If I'm fast enough, I can quickly swap to one of the other 2 and the tool loads fine.  Curious if it's crashing due to trying to calculate too many permeations.

Console pauses "before potential out-of-memory crash" in Chrome.

![image](https://user-images.githubusercontent.com/90156523/132140611-94df33a7-e1cc-4fc9-8219-7c0ebec21eeb.png)

![image](https://user-images.githubusercontent.com/90156523/132140601-cfa93032-db95-471f-bb60-5dd155599c5d.png)

Let me know what other info I can provide.

**Comment by Mijago** [comment]
Hi, please try the second version of the tool: https://mijago.github.io/D2ArmorPicker/#/v2
There are still some things missing before I can push it as the main version, but it is fully functional.

**Comment by BastaAZ** [comment]
Confirmed that worked.  Seems just to be related to memory use, which is much lower in V2.
