### ISSUE TITLE
add i18n support

### ISSUE THREAD

**Issue by PaiJi** [Mijago/D2ArmorPicker#38]
Hi, i want to know is there any possible to add i18n support?  i can contribute zh-cn translation.
and thanks for this brilliant tools ! i dont even know i can reach 300+ armor.

**Comment by Mijago** [comment]
Hi! I have to be honest, I do not see a reason to add i18n to D2ArmorPicker as of now.
I like to keep it simple for both the user and the developer (myself), and full i18n makes it hard for me to develop new features, as I have to translate every text. Also, english is a widely used language on the web.

**Comment by PaiJi** [comment]
Thanks for your reply and great work :)
