### ISSUE TITLE
Could it be that the Resilience HP calculation is wrong?

### ISSUE THREAD

**Issue by ahydronous** [Mijago/D2ArmorPicker#39]
5 bodyshots from The Last Word do 39 damage each, for 195 damage. According to armor picker, that should require 80 resilience to survive (196hp). However, you survive it at 6 resilience.

**Comment by Mijago** [comment]
Hi, I took the numbers from some destiny wiki and didn't calculate them myself. I can of course check if I made a typo, but I am quite sure is double checked it.

Note that ingame numbers are quite often rounded up, which means it could be that you deal 38.1 damage (or something), leading to rounding issues. I am not a spreadsheet person, they may have a clue of what's happening.

I'll check the numbers on the weekend.

**Comment by Mijago** [comment]
Here are the current values: https://d2.destinygamewiki.com/wiki/Resilience
What you see ingame is probably a rounded value.
