### ISSUE TITLE
Charge Harvester mod taken into account when it shouldn't

### ISSUE THREAD

**Issue by ozone** [Mijago/D2ArmorPicker#41]
I have a Necrotic Grip with 8 base recovery and a Charge Harvester mod (-10 recovery) in my inventory. D2ArmorPicker counts it as 0 recovery in the results tab, as if the mod was part of the armor. I don't know if the issue is specific to this mod, but I don't recall other mods causing trouble.

The Necrotic Grip in question:
![image](https://user-images.githubusercontent.com/20775/133939232-2921a118-3b8e-451d-87bc-27082ed7de56.png)

D2ArmorPicker's view of this iitem:
![image](https://user-images.githubusercontent.com/20775/133939253-2765a164-8515-43ce-ba68-f34da8116867.png)

**Comment by ozone** [comment]
Just for confirmation: once I remove the Charge Harvester mod, everything works as expected.

**Comment by Mijago** [comment]
Hi  this is an error due to the api clipping it at 0. I have to take a look at what DIM does to solve it.

There's already an issue for this, so I'll close this one for now: #29
