### ISSUE TITLE
Armor picker missing options

### ISSUE THREAD

**Issue by justintricate** [Mijago/D2ArmorPicker#46]
![Untitled](https://user-images.githubusercontent.com/47122570/135045045-80207606-6b50-4b40-bc9f-1f89c10bf00b.png)

A few weeks ago I used armor picker to generate a 100mob-100rec-100int-50dis build for trials. Messing with it today, I am unable to get it to replicate that same build.

As you can see, the armor picker is convinced there is no way to get to 50 dis. Combat mods I am using: powerful friends, radiant light, whisper of chains/conduction fragments. (Verified here: https://guardianforge.net/build/01609f2c-1ef3-414b-9235-ddf5e164d3b3)
![Screenshot 2021-09-28 023452](https://user-images.githubusercontent.com/47122570/135043606-cf1434aa-6bf8-4f6e-b6ed-0ace1625e5b9.png)

I actually found this set of gear in the armor picker, so it definitely *sees* each piece.
![Screenshot 2021-09-28 024508](https://user-images.githubusercontent.com/47122570/135045109-1884e319-06e6-4a1f-9eb9-e163c0cff78b.png)

With powerful friends + a single minor mobility mob, I am at 101 on my actual gear. So 96 pre-mod. Armor picker says I should be at 89, and neither the tool nor myself can figure out where the math is going wrong. Unclear.. it's bang on with the recovery and intellect values, too. I know that.

So, I guess unclear how I am at 101 mobility in-game, but unable to replicate that with this gear, with the tool?

**Comment by Mijago** [comment]
Hi, can you please show me images of all 5 armor pieces?

**Comment by justintricate** [comment]
![helm](https://user-images.githubusercontent.com/47122570/135131272-35a3d3de-1014-4416-b8d7-45de8c0299bd.PNG)
![gloves](https://user-images.githubusercontent.com/47122570/135131282-07de6d93-99eb-4e12-9961-9539c02d73ee.PNG)
![chest](https://user-images.githubusercontent.com/47122570/135131277-063fcf6f-e17c-4343-b3b1-5ba0cc1e1573.PNG)
![boots](https://user-images.githubusercontent.com/47122570/135131275-43e607ec-88bf-4266-a309-899b7e43a747.PNG)
![cloak](https://user-images.githubusercontent.com/47122570/135131279-0f875599-bd5c-42c0-ae20-38296ae801d9.PNG)

For easier viewing, that guardianforge link may help as well-- https://guardianforge.net/build/5589ab1a-734b-4616-8689-683d624dcaee

**Comment by Mijago** [comment]
That Vest goes above 42. The API cuts items off from [0, 42], which leads to incorrect values.
V2 shows a warning in such cases for two days now. Remove all positive/negative mods that move the stat(s) above 42 / below 0.
