### ISSUE TITLE
V2 can't find armor set that V1 can

### ISSUE THREAD

**Issue by wanton7** [Mijago/D2ArmorPicker#51]
In v2 I can't select strength 60 and I have the same set expanded that v1 finds
![d2armor_picker_v2_problem_1](https://user-images.githubusercontent.com/1009930/137603231-9a7b7f30-b393-4881-97f8-3804879c75f6.png)

But in v1 I can select strength 60
![d2armor_picker_v2_problem_2](https://user-images.githubusercontent.com/1009930/137603235-a24fbd97-3365-42bf-82c5-2cf314d61a42.png)

**Comment by Mijago** [comment]
Thanks. Can you deactivate the "try to optimize wasted stats" settings. I am quite sure the issue is related to this feature

**Comment by wanton7** [comment]
Yes that fixed it.
