### ISSUE TITLE
Potential Bug In Results Section With Stats Counter & Mods

### ISSUE THREAD

**Issue by HHTTRS** [Mijago/D2ArmorPicker#57]
Hello Mijago,

Firstly I would like to say a huge thank you for this system you've built, it's brilliant!

This helped me create my first double hundred stat loadout for PvE with ease, as well as my first dedicated PvP set with the stats I wanted. They've helped me enjoy PvE and PvP even more due to be being better equipped, so thanks again!

With all the PvP changes coming out in D2 next week, then I want a new PvP loadout but I'm having an issue this time around.

Please can you help confirm if I'm missing something, or if it's a system limitation/bug?

I've saved the configuration and tried to copy it to send to you, but it's a large paragraph full of random text, so don't think it's of use to you? If not, I can send pictures over PSN worst case, if you need to see what it is you're looking at. Saying that, you may be able to replicate this yourself by simply selecting an Exotic, spec'ing the same Stats and Mods as me (as per below).

Essentially, I need 120 Recovery so that the two Mods I run (Charge Harvester & Stack On Stacks), which deduct 10 Recovery each (so 20 in total), means I still have 100 Recovery at the end.

Recovery Loadout:

The Stag - 10 (Masterworked)
Gloves - 4 (Masterworked)
Chest - 18 (Masterworked)
Boots - 28 (Masterworked)
Bond - 2 (Masterworked)

Recovery Subtotal: 62

Mod Deductions: -20 Recovery

Recovery Subtotal: 42

Mod Enhancements: 50 Recovery (5 Recovery Mods)

Recovery Total: 92

However, the D2 Armour Picker V2 is saying that the total is actually 102, but this is not the case as far as I can see (I've replicated the exact same issue across multiple Exotics with the same Stats/Mods loadout).

I can confirm that:

- I'm not using any Stasis Fragments or Aspects (I'm running Arc/Void subclass)
- Not using any other Mods, other than what's been stated, which affect ability cooldowns
- Only opted for 100 in Recovery and 60 in Resilience, with 0 in all the other abilities
- No Element Affinity Restrictions
- Stag selected for Exotic. (but happens with any Exotic and same Stats/Mods loadout)
- No Disabled Items
- No warning next to the selected loadout I.e. no issues found with it

I have a little bit of web coding knowledge but not much and am by no means a coder. I just have a bit of a basic understanding and do software testing as a job. As a result of this, I can appreciate the time and effort gone into it, you've got great skill. I bought you a coffee on Ko-fi under HHDnB (my PSN ID), though apologies for the Reddit message (from HH__66), I forgot you said to contact you on here, so please ignore that.

Many Thanks.

Harry

**Comment by Mijago** [comment]
That sounds like your items are not masterworked, but D2ArmorPicker per default assumes that all items are masterworked.
Can you test that?

**Comment by HHTTRS** [comment]
Hi Mijago,

Apologies if I'm not following correctly, so please bear with me. I thought that when the D2 Armour Picker assumes that items which aren't Masterworked are Masterworked, then it applies the +12 Stats (+2 for each ability) to the non-Masterworked item, so that it behaves as if it was Masterworked during the calculations?

I'm in Destiny 2 now with the exact loadout on my Warlock, as per the D2 Armour Picker and every ability Stat matches back perfectly (/would match perfectly once I've Masterworked The Stag & Gloves), except for the Recovery Stat which is miscounting 10 and I've just seen now, that the Discipline is actually 10 less in the Total on D2 Armour Picker than it should be too. So I think that the system is deducting the -10 penalty to Recovery, from one of the Mods (Charge Harvester/Stack On Stacks), from Discipline instead by mistake, despite showing the -20 penalty in the Recovery column (please see attached picture highlighting this called D2 Armour Picker Query).

To confirm, here's my loadout:

The Stag (non-Masterworked)

- Mobility +14  (+16 when Masterworked)
- Resilience +10 (+12 when Masterworked)
- Recovery +8 (+10 when Masterworked)
- Discipline +9 (+11 when Masterworked)
- Intellect +10 (+12 when Masterworked)
- Strength +12 (+14 when Masterworked)

Thorium Holt Gloves (non-Masterworked)

- Mobility +12  (+14 when Masterworked)
- Resilience +18 (+20 when Masterworked)
- Recovery +2 (+4 when Masterworked)
- Discipline +22 (+24 when Masterworked)
- Intellect +10 (+12 when Masterworked)
- Strength +2 (+4 when Masterworked)

Iron Truage Vestaments (Masterworked)

- Mobility +4
- Resilience +18
- Recovery +18
- Discipline +18
- Intellect +8
- Strength +12

Iron Forerunner Boots (Masterworked)

- Mobility +4
- Resilience +8
- Recovery +28
- Discipline +18
- Intellect +8
- Strength +12

Holdfast Bond (Masterworked)

- Mobility +2
- Resilience +2
- Recovery +2
- Discipline +2
- Intellect +2
- Strength +2

Stats subtotal (my manual calculations & D2 Armour Picker both match perfectly at this step):

- Mobility +36 (+40 when The Stag & Gloves Masterworked)
- Resilience +56 (+60 when The Stag & Gloves Masterworked)
**- Recovery +58 (+62 when The Stag & Gloves Masterworked)**
**- Discipline +69 (+73 when The Stag & Gloves Masterworked)**
- Intellect +38 (+42 when The Stag & Gloves Masterworked)
- Strength +40 (+44 when The Stag & Gloves Masterworked)

Mod deductions:

- Recovery -10 (Charge Harvester - Gloves)
- Recovery -10 (Stack On Stacks - Boots)

Stats subtotal:

- Mobility +36 (+40 when The Stag & Gloves Masterworked)
- Resilience +56 (+60 when The Stag & Gloves Masterworked)
**- Recovery +38 (+42 when The Stag & Gloves Masterworked)**
**- Discipline +69 (+73 when The Stag & Gloves Masterworked)**
- Intellect +38 (+42 when The Stag & Gloves Masterworked)
- Strength +40 (+44 when The Stag & Gloves Masterworked)

Mod Enchantments:

- Recovery +10 (The Stag)
- Recovery +10 (Gloves)
- Recovery +10 (Chest)
- Recovery +10 (Boots)
- Recovery +10 (Bond)

Stats Total (my calculations which match (/would match once Masterworked) with Destiny 2):

- Mobility +36 (+40 when The Stag & Gloves Masterworked)
- Resilience +56 (+60 when The Stag & Gloves Masterworked)
**- Recovery +88 (+92 when The Stag & Gloves Masterworked)
- Discipline +69 (+73 when The Stag & Gloves Masterworked)**
- Intellect +38 (+42 when The Stag & Gloves Masterworked)
- Strength +40 (+44 when The Stag & Gloves Masterworked)

Stats Total (D2 Amour Picker calculations which doesn't match for Recovery & Discipline):

- Mobility +36 (+40 when The Stag & Gloves Masterworked)
- Resilience +56 (+60 when The Stag & Gloves Masterworked)
**- Recovery +98 (+102 when The Stag & Gloves Masterworked)
- Discipline +59 (+63 when The Stag & Gloves Masterworked)**
- Intellect +38 (+42 when The Stag & Gloves Masterworked)
- Strength +40 (+44 when The Stag & Gloves Masterworked)

As per the attached picture (D2 Armour Picker Query), you can see that the Recovery and Discipline Stats aren't displaying the correct values in the D2 Armour Picker (but all other Stats are correct), which is why I think there's potentially a bug somewhere. Due to the Intellect being 10 above it should be and Discipline being 10 down to what it should be, so imagine it's because of the D2 Armour Picker deducting one of the -10 Recovery penalties for Charge Harvester from Discipline, instead of Intellect.

I've also attached my Warlock (Destiny 2 - Warlock Loadout), showing the actual in game values and what I did my manual calculations on.

Many Thanks.

Harry
![D2 Armour Picker Query](https://user-images.githubusercontent.com/40612944/144600263-942121a5-91ed-48cc-a966-79e20abf2226.png)
![Destiny 2 - Warlock Loadout](https://user-images.githubusercontent.com/40612944/144600285-acee1cf2-bf07-4377-a44b-fdf79c7982db.jpg)

**Comment by Mijago** [comment]
That image from D2AP shows that there is something wrong. I'll investigate this soon.
60-20+50 = 90, so the result it shows is incorrect. Thank you!!

**Comment by HHTTRS** [comment]
Thanks Mijago, I really appreciate all of your help and time as well as the continued support, it's great work :)

**Comment by Mijago** [comment]
This has been fixed in the meantime.
