### ISSUE TITLE
Slow loading times

### ISSUE THREAD

**Issue by Darius-Tanz** [Mijago/D2ArmorPicker#58]
I know it is not a priority but since last month I have seen a huge uptick in the time the app takes to load. I tried in different browsers and computers, updating manifest and the cache takes a long time and if the app sits idle for a couple hours it seems to get bricked. Let me know if there are any details I can provide.

**Comment by jpmaradiaga** [comment]
+1

**Comment by Mijago** [comment]
I have a fix for the inventory thing for a month, but as I took a short break from developing it went untested and thus not pushed. I'll come back to developing and fixing over the course of the next week, and then I can finally push this!

For the problem when you let the page open: I think the angular framework has some memory leaks that I could not pinpoint, some weird interaction of browser-IndexedDB-Angular. I'll look into this too.

Thank you for the report!
