### ISSUE TITLE
Eyes of Another World

### ISSUE THREAD

**Issue by datageek** [Mijago/D2ArmorPicker#59]
I've tried on Firefox and Chrome. I cannot build any sets with this helm.

**Comment by Mijago** [comment]
Hi,  can you please tell me what you changed? I am currently writing a FAQ and I think this could be a good point on that list :)

**Comment by datageek** [comment]
It still doesn't work for me, but my assumption was that since it was an S1 item that I acquired at the start of D2 that it was somehow causing an issue. For reference, I obtained the item in the first 2-3 months of D2's release and then hadn't touched the game again until this past September. So it was an 1100 item that I figured was somehow bugged.

**Comment by Mijago** [comment]
Ah, Armor 1.0 is disabled on purpose. Just collect it from collections and it'll work!
