### ISSUE TITLE
add the option to exclude armour pieces

### ISSUE THREAD

**Issue by remo-bonk** [Mijago/D2ArmorPicker#60]
I'd like to create builds but choose to exclude certain pieces of armour from being used (42 mobility blue gauntlets)

**Comment by Mijago** [comment]
This feature already exists:
![image](https://user-images.githubusercontent.com/3903469/145631128-fac837c7-c483-49f2-a2b0-d127c91260d6.png)

**Comment by remo-bonk** [comment]
oops sorry
