### ISSUE TITLE
Cooldown times are wrong

### ISSUE THREAD

**Issue by ahydronous** [Mijago/D2ArmorPicker#67]
I just tested it in-game, and the cooldown times do not match up with the one's in D2Armorpicker.

Instead the match up with CoolGuy's cooldown times. Here they are (apologies that they are an image, that is how they were posted online):

Supers:
![image](https://user-images.githubusercontent.com/57762816/149136708-8b64dc7e-ab0e-4da2-9dc2-9d6088ee3d98.png)

Class:
![image](https://user-images.githubusercontent.com/57762816/149136766-3a53778a-45d5-4395-9e29-5d9927fb9837.png)

Grenades:
![image](https://user-images.githubusercontent.com/57762816/149136834-d25a6324-14fa-4034-9a27-33b36ad0cfc7.png)

Melees:
![image](https://user-images.githubusercontent.com/57762816/149136894-73e24624-1701-4d63-a858-1376ad53f4e7.png)

**Comment by Mijago** [comment]
Closed in favor of https://github.com/Mijago/D2ArmorPicker/issues/67
