### ISSUE TITLE
D2Armorpicker

### ISSUE THREAD

**Issue by Drb01-hub** [Mijago/D2ArmorPicker#69]
Hello,

I love this program but for the last week at least, it doesnt seem to be working. I open it, sign in, and when I attempt to select a piece of armor, say exotic, it doesn;t load any option.  Even clearing everything and selecting a build from general gear,  It refreshes but displays nothing.

Help
Steve

**Comment by joshrosario310** [comment]
This might be similar to what I'm experiencing as well. It was working fine and then I believe I clicked some sort of disable on a class piece in one of the results, now there are no results, I can't select exotics. Tried a Clear Everything as well as a page & cache refresh. There are no items in the Disabled Armor Pieces section.

**Comment by Mijago** [comment]
Hi, can you please export your configuration and add it here? :)

**Comment by joshrosario310** [comment]
I tried deleting the cookies manually and clearing the browser cache this morning and it's working for me again, I'm not sure why I couldn't get this to work last week.

**Comment by Mijago** [comment]
This issue has been fixed in the meantime.
