### ISSUE TITLE
Some people are stuck in a login loop

### ISSUE THREAD

**Issue by Mijago** [Mijago/D2ArmorPicker#7]
A very nice, helpful guardian gave me the following logs: 

![image](https://user-images.githubusercontent.com/3903469/127552821-33bd4bbf-9074-4792-bfbe-f4da1db7f457.png)
![image](https://user-images.githubusercontent.com/3903469/127552847-d68685cf-d7c7-467f-9f8e-8315d74ca21f.png)

Message-Data: `{"ErrorCode":2102,"ThrottleSeconds":0,"ErrorStatus":"ApiKeyMissingFromRequest","Message":"Please add valid X-API-Key header to request.  Visit https://www.bungie.net/developer for details.","MessageData":{}}`

**Comment by Mijago** [comment]
Seems to be some kind of race condition in the login process. I'll further investigate.

**Comment by Mijago** [comment]
It says the Api key is missing, but it sends the API key and the Bearer Token from the previous step.
Two of the persons that have this problem are console players. I did not get to ask more persons (yet).

**Comment by jpmaradiaga** [comment]
I am having the same issue, here is the stack

![image](https://user-images.githubusercontent.com/44245417/127695691-4e56cb5e-b055-49ee-b992-f4673f8ea7fe.png)

**Comment by mpentax** [comment]
Reproduces on my account. tested with firefox. chrome and edge + safari and chrome on my mac. tried clearing site data (yes, this includes indexeddb) and also tried revoking and regranting access through the bungie site. Also worth noting the site worked yesterday so this must be some change to my account since them (maybe a specific armor piece?)

![armorerror](https://user-images.githubusercontent.com/10182959/127703665-5827bd8b-9277-4bc5-8768-ac8b401d34d1.png)

Let me know if you need any more data and I'll be happy to help.

**Comment by Mijago** [comment]
> Reproduces on my account (PC). tested with firefox, chrome and edge + safari and chrome on my mac. tried clearing site data (yes, this includes indexeddb) and also tried revoking and regranting access through the bungie site. Also worth noting the site worked yesterday so this must be some change to my account since then (maybe a specific armor piece?)
> 
> ![armorerror](https://user-images.githubusercontent.com/10182959/127703665-5827bd8b-9277-4bc5-8768-ac8b401d34d1.png)
> 
> Let me know if you need any more data and I'll be happy to help.

This is another variant of this issue, and is resolved now.

**Comment by Mijago** [comment]
@mpentax @jpmaradiaga Can you please log into the tool again and see whether it works now?

**Comment by mpentax** [comment]
> 
> 
> @mpentax @jpmaradiaga Can you please log into the tool again and see whether it works now?

Works for me. Thanks!

**Comment by jpmaradiaga** [comment]
Mine doesn't crash, it just keeps updating the manifest forever.
![image](https://user-images.githubusercontent.com/44245417/127720675-bf3d0860-8d95-4926-a50c-a35b28cb773c.png)
