### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by JMX09** [Mijago/D2ArmorPicker#72]
Currently having issues signing into D2ArmorPicker through Bungie.net; tried clearing cache, reset my entire history and used a different browser, no luck signing in.

**Comment by Davixk** [comment]
same here

**Comment by everwarez** [comment]
I've tried multiple browsers and different crossplay logins. I'll hit approve and it will take me bakc to the login screen.

**Comment by thedarkboo** [comment]
Same, getting error logging in. Here is the console output.
```
PRODUCTION? true
 {
       code: '4eb2e233ff2452f14da76877ff29906a'
 }
Setting new auth code
Generate tokens with the new code
Generate auth tokens refresh based on refresh_token: false
Success with tracking page view!
{
    "err": {
        "headers": {
            "normalizedNames": {},
            "lazyUpdate": null
        },
        "status": 400,
        "statusText": "OK",
        "url": "https://www.bungie.net/Platform/App/OAuth/Token/",
        "ok": false,
        "name": "HttpErrorResponse",
        "message": "Http failure response for https://www.bungie.net/Platform/App/OAuth/Token/: 400 OK",
        "error": {
            "error": "invalid_grant",
            "error_description": "AuthorizationCodeInvalid"
        }
    }
}
Clearing refresh token
Clearing auth code
Clearing access token
Clearing refresh token
Now navigate to /
```

**Comment by Mijago** [comment]
Hi, I just woke up and rushed to the PC for you all :D

Up to now, it was still configured to forward to https://mijago.github.io/D2ArmorPicker, which worked perfectly. Github automatically forwards it to the new URL - but it seems like Github or Bungie shadow changed something. 
Well, I configured it to forward to https://d2armorpicker.com/ now, and it works again.

Thank you all so much for letting me know (and for giving me a heart attack right after waking up)! :D
