### ISSUE TITLE
Stuck in Error Loop - PSN

### ISSUE THREAD

**Issue by Lludara** [Mijago/D2ArmorPicker#75]
Upon attempting to log in using Firefox, Edge, and Chrome. 

Opened link in new tab as well - Attempts to log into my account but as soon as the Sony window appears, it says "an error has occurred" and auto reloads the page in an infinite loop

**Comment by Lludara** [comment]
When I click to login, it kicks me over to what would typically be the page where I log into my PSN account to then authorize use of the API. However, that page continuously reloads after giving me about a .25s message that an error occurred. 

I was able to get it to work on Edge, but am still having issues on Firefox

**Comment by Mijago** [comment]
Closed in favor of https://github.com/Mijago/D2ArmorPicker/issues/105
