### ISSUE TITLE
Stuck in a loop

### ISSUE THREAD

**Issue by MJOLNIRMKV** [Mijago/D2ArmorPicker#77]
When I click on "login" it brings me to the screen where I can select the desired stats but after about 5 seconds it brings me back to the page with the login button. Am I doing something wrong? Or has anyone else experienced this and know what to do?

**Comment by Mijago** [comment]
The Bungie API is down right now. D2AP logs you out until it is online again.
Also, note that it might take a while until Bungie updates the Manifest.

I will add the Arc 3.0 fragments within the next hours.
