### ISSUE TITLE
Login Loop - CORS Issue - PSN

### ISSUE THREAD

**Issue by RTG-CJardin** [Mijago/D2ArmorPicker#78]
<img width="1502" alt="Screen Shot 2022-09-13 at 1 04 03 PM" src="https://user-images.githubusercontent.com/79104029/189963389-5e1907d5-0f8d-41e7-afae-4326f4c398c9.png">

Attempted to login with several browsers including mobile devices and each result in a 504 response to `https://www.bungie.net/Platform/Destiny2/2/Profile/4611686018487327820/?components=205,201,103,102,304,300`

**Comment by Mijago** [comment]
Bungie API is currently down. Nothing I can do about it.

**Comment by RTG-CJardin** [comment]
@Mijago oh right! bad timing. sorry about that
