### ISSUE TITLE
I'll look at this hopefully tomorrow evening. If not, then at the weekend.

### ISSUE THREAD

**Issue by Fzt310** [Mijago/D2ArmorPicker#88]
I'll look at this hopefully tomorrow evening. If not, then at the weekend.

_Originally posted by @Mijago in https://github.com/Mijago/D2ArmorPicker/issues/80#issuecomment-1290848262_

**Comment by Fzt310** [comment]
I’m getting this problem as well how did I fix it ?

**Comment by TheMojoDojo** [comment]
Currently the API is down, you can check @BungieHelp on Twitter for updates
