### ISSUE TITLE
D2 Armor Picker returning to login screen 1/26/2023 Need Fix

### ISSUE THREAD

**Issue by buckeye920** [Mijago/D2ArmorPicker#93]
D2 Armor Picker returning to login screen 1/26/2023 Need Fix

**Comment by TheMojoDojo** [comment]
Could you detail the steps you took up to this problem?

**Comment by buckeye920** [comment]
Just logged in, clicked accept, screen populated for a brief second then returned me to the log in page. Tried logging out, then sign in but just repeats the circle.

**Comment by buckeye920** [comment]
I had a friend login in and he has no problem so problem is most likely on my end.

**Comment by buckeye920** [comment]
tried on a different computer still same issue.

**Comment by wholenineyards** [comment]
I am having this issue too. Click login > click Approve >  the main UI appears for a split second then boots me back the login page. I've tried logging out and back into PSN. I've tried Chrome, incognito Chrome (no cookies) & Edge, all the same behaviour. API is currently working for DIM.

**Comment by wholenineyards** [comment]
I'm seeing this too, then realised the API is down for maintenance.

**Comment by matthewbahr** [comment]
This is an issue for me both on beta.d2armorpicker as well as main site. 

Looking at network logs I see an error 503 when calling GET on https://www.bungie.net/Platform/Destiny2/Manifest/

**Comment by TheMojoDojo** [comment]
This is correct, API is not working at the moment. D2AP will be back up once Bungie fixes everything on their side
