### ISSUE TITLE
Add a way to enable a toggle to only pick Artifice armor

### ISSUE THREAD

**Issue by snnacks** [Mijago/D2ArmorPicker#96]
Currently with D2ArmorPicker there is no way to only be shown armor combinations with armor that is artifice. This would be an amazing feature because in Lightfall artifice armor is becoming much more important with the +3 mod slots.

**Comment by CameronSWilliamson** [comment]
You can set that through the Armor limitation section of the website by selecting this option in the mod limitations section.

![image](https://user-images.githubusercontent.com/81795106/220838304-6bb48c9f-534e-4501-8560-168bb3850f59.png)

**Comment by snnacks** [comment]
Thank you! I thought I had looked everywhere, but it was right there the entire time.

**Comment by Mijago** [comment]
> Thank you! I thought I had looked everywhere, but it was right there the entire time.

Also check out the beta. It is not near being done and has a few quirks, but the basic artificer logic is there: https://beta.d2armorpicker.com/#/

**Comment by CameronSWilliamson** [comment]
@snnacks I was about to start making a pull request and all that stuff and then I realized that you *can* in fact do it. Thanks for all the good work @Mijago!
