### ISSUE TITLE
Not recognizing certain exotics in inventory or vault.

### ISSUE THREAD

**Issue by IFoundTheSauce** [Mijago/D2ArmorPicker#97]
I have just started using this to attempt to make a build around Starfire protocol, however, armor picker does not say I own it. it is grayed out for selection even though it's currently on my warlock. I tried to move it around to my vault or my inventory then reload and I even tried clearing the cache and restarting the application entirely. Still, it does not show up. there are a few other exotics that also aren't showing up when I went to look if it was just Starfire protocol but it is not. It shows most of my exotics just fine. The others that are missing are Crown of Tempests and Nezarec's Sin. Not sure if I'm missing something.

**Comment by TheMojoDojo** [comment]
Judging by the situation. I believe it's highly likely that the instances of exotics that are greyed out are "armor 1.0". D2AP ignores Armor 1.0 as they don't play nicely with mods. Your best bet would be to grab a roll from the collections tab, or to procure a newer updated version of the exotic. 

Without images of the exotic in question from in-game, I cannot be 100% sure, but I am around 98% sure of this

**Comment by IFoundTheSauce** [comment]
Ooooh, thanks! yeah they are some of the first exotics I ever got and I have never used them till now, I didn't even remember that armor got changed like that. I'll grab a roll from there then real quick and see if it shows up.

**Comment by IFoundTheSauce** [comment]
Oh Yeah, it was that, showed up with no problem once I got one from collections. Thanks again!
