### ISSUE TITLE
Returned to login screen bug on 3/9/2023

### ISSUE THREAD

**Issue by etanfx** [Mijago/D2ArmorPicker#98]
I'm having the returning login screen bug. After logging in it shows the site for a second only to swap back to login screen. Cleared all site data and cookies, tried incognito and a different browser and nothing works. Fix needed.

**Comment by TheMojoDojo** [comment]
API is not working at the moment. D2AP will be back up once Bungie fixes everything on their side

**Comment by cpickinpaugh** [comment]
3/16, Same issue, is API still down?

**Comment by TheMojoDojo** [comment]
Scheduled maintenance, it's only going to be down temporarily

**Comment by cpickinpaugh** [comment]
> 

Awesome. Thanks.

**Comment by ProjectGSX** [comment]
more maintenance?  It would be nice if this return to login bug was made so that a maintenance banner was shown so we know the sites down.

**Comment by Mijago** [comment]
Maintenance banner is on our todo list.
